Add auxiliar widget beside PlutoColumnTitle icon
oxeanbits/pluto_grid pull request #10
Opened 2023-07-27 17:34 UTC by gustoliveira

## Description

This PR aims to allow to create an auxiliar widget beside PlutoColumnTitle icon, that can be passed by implementing the PlutoColumnMenuDelegate.

It can be used to add a verification if the column is filter, to remove the filter, etc.

This can be controlled by adding a conditional statement using the PlutoColumn received by the method to show only in the right column. Can controlled some type of state in the onSelected method too.

## How to smoke

- You can create such as the bellow.

```
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

enum PlutoGridColumnMenuItem {
  unfreeze,
  freezeToStart,
  freezeToEnd,
  hideColumn,
  setColumns,
  autoFit,
  setFilter,
  resetFilter,
}

class GridColumnMenu
    implements PlutoColumnMenuDelegate<PlutoGridColumnMenuItem> {
  final BuildContext context;

  GridColumnMenu(this.context);

  @override
  Widget? auxiliarWidgetIndicator(PlutoColumn column) {
    return IconButton(
      icon: const Icon(Icons.filter),
      onPressed: () {
        print("You pressed in '${column.title}' column");
      },
    );
  }

  @override
  List<PopupMenuEntry<PlutoGridColumnMenuItem>> buildMenuItems({
    required PlutoGridStateManager stateManager,
    required PlutoColumn column,
  }) {
    return const [
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.unfreeze,
        enabled: true,
        child: Text(
          'Unfreeze',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.freezeToStart,
        enabled: true,
        child: Text(
          'Freeze To Start',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.freezeToEnd,
        enabled: true,
        child: Text(
          'Freeze To End',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.hideColumn,
        enabled: true,
        child: Text(
          'Hide Column',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.setColumns,
        enabled: true,
        child: Text(
          'Set Columns',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.autoFit,
        enabled: true,
        child: Text(
          'Auto Fit',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.setFilter,
        enabled: true,
        child: Text(
          'Set Filter',
          style: TextStyle(color: Colors.white),
        ),
      ),
      PopupMenuItem<PlutoGridColumnMenuItem>(
        value: PlutoGridColumnMenuItem.resetFilter,
        enabled: true,
        child: Text(
          'Reset Filter',
          style: TextStyle(color: Colors.white),
        ),
      ),
    ];
  }

  @override
  Future<void> onSelected({
    required BuildContext context,
    required PlutoGridStateManager stateManager,
    required PlutoColumn column,
    required bool mounted,
    required PlutoGridColumnMenuItem? selected,
  }) async {
    print('You tap in ${selected.toString()}');
  }

  @override
  Future<PlutoGridColumnMenuItem?>? showColumnMenu({
    required BuildContext context,
    required Offset position,
    required List<Widget> items,
    Color backgroundColor = Colors.white,
  }) {
    if (items.isEmpty) return null;

    final List<PopupMenuItem<PlutoGridColumnMenuItem>> finalItems =
        items.cast<PopupMenuItem<PlutoGridColumnMenuItem>>();

    return showDialog(
      context: context,
      builder: (_) {
        return Center(
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(5),
            ),
            height: 330,
            width: 300,
            child: Column(children: itemsList(finalItems)),
          ),
        );
      },
    );
  }

  List<Widget> itemsList(List<PopupMenuItem<PlutoGridColumnMenuItem>> items) {
    List<Widget> itemsList = [];

    itemsList.add(const Padding(padding: EdgeInsets.symmetric(vertical: 5)));

    for (var item in items) {
      var child = item.child;
      if (child == null) continue;

      itemsList.add(
        GestureDetector(
          child: Container(
            decoration: BoxDecoration(
              color: Colors.blue,
              borderRadius: BorderRadius.circular(5),
            ),
            height: 30,
            width: 280,
            child: Center(child: child),
          ),
          onTap: () {
            Navigator.pop(context, item.value);
          },
        ),
      );

      itemsList.add(const Padding(padding: EdgeInsets.symmetric(vertical: 5)));
    }

    return itemsList;
  }
}
```

## Smoke Running

2023-07-31 23:11 UTC, rodiguif requested changes

2023-07-31 23:11 UTC, rodiguif commented on lib/src/ui/columns/pluto_column_title.dart
> +    Widget? auxiliarIndicator;
I just didn't like the `auxiliar` name. :sweat_smile: 

How about `leftIcon` or `leadingIcon`? I don't know either.

2023-08-01 14:12 UTC, vpinheiro38 submitted a review, later dismissed

2023-08-01 14:12 UTC, victorpinheirodev commented on lib/src/ui/columns/pluto_column_title.dart
> +        auxiliarIndicator ?? Container(),
@gustoliveira Some places are still with the name auxiliar. I agree with Rodrigo that the name is not good. Align with the updated name. :raising_hand_man:

2023-08-01 20:37 UTC, rodiguif approved these changes

2023-08-01 21:37 UTC, merged