Shortcuts
oxeanbits/pluto_grid pull request #19
Opened 2024-04-16 14:28 UTC by Leonardo1952

2024-04-16 18:29 UTC, Leonardo1952 commented
PR Shortcut: https://github.com/flutter/flutter/pull/136854

2024-05-09 18:28 UTC, tiagogoncalves requested changes

2024-05-09 18:28 UTC, tiagogoncalves commented on demo/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
why remove this file?

2024-05-09 18:51 UTC, Leonardo1952 commented on demo/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
In reality I don't even understand why it went up, it's a file that had my local address:

![Screenshot 2024-05-09 154941](https://github.com/oxeanbits/pluto_grid/assets/53130191/b7eb4d1f-79d3-406c-b414-768f7fc4e75d)

2024-05-10 12:01 UTC, tiagogoncalves approved these changes

2024-05-10 12:16 UTC, rodiguif approved these changes

2024-05-10 12:17 UTC, merged